"""empty message

Revision ID: 2dc3254d2ca4
Revises: 396cb62d9b8f
Create Date: 2023-06-09 06:05:23.076475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc3254d2ca4'
down_revision = '396cb62d9b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])
        batch_op.drop_column('size')
        batch_op.drop_column('fish_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fish_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
