"""Initial migration

Revision ID: 396cb62d9b8f
Revises: 476329812b92
Create Date: 2023-06-08 19:58:56.805697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396cb62d9b8f'
down_revision = '476329812b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fish',
    sa.Column('fish_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('fish_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fish')
    # ### end Alembic commands ###
